### PR TITLE
Added signature and Dbf.Write(Stream) method

### PR DESCRIPTION
**Pull request by NicholasNoise**
Downgrade framework to 4.5 - higher version is not necessary.
Added signature - strong assembly name.
Added Dbf.Write(Stream) method - for web project that send files as stream.
Updated nuspec.

### CODE REVIEW

**Comment by NicholasNoise** [comment]
To pack nuget I've used command:
` C:\Workspace\nuget.exe pack "C:\Workspace\github\dBASE.NET\dBASE.NET\dBASE.NET.nuspec" -NonInteractive -OutputDirectory C:\Workspace\github\dBASE.NET\dBASE.NET -Properties Configuration=release -Verbosity Detailed`

**Comment by henck** [comment]
Everything worked beautifully. I think that `-Properties Configuration=release` may have been the problem. I had built my release version, then probably packaged the debug version. I can see that my debug version DLL file date is as a long time ago.

I used `nuget push dBASE.NET.1.2.0.nupkg (key) -Source https://api.nuget.org/v3/index.json` to push the package. It's now available on nuget.

Will you please verify that this version does indeed contain your latest changes?

**Comment by NicholasNoise** [comment]
Verified!
This time everything went well, thank you!

**Comment by henck** [comment]
No, thank you for doing the signing and nuget setup. Saved me much googling around and hairpulling.

**Pull request merged**
