### PR TITLE
Allow custom encodings.

### PR DESCRIPTION
**Pull request by NicholasNoise**
I have legacy project with some dbf exports that should be ported from OleDb to some other solution, because Mono has no implementation of OleDb.
Your solution is quite useful, but I require custom encoding - CP866.

### CODE REVIEW

**Comment by henck** [comment]
Thank you! I've gone through the code, and I see you've made the encoding an optional field in the `Dbf` constructor. Thanks for adding a test case, as well. I am merging this branch.

**Comment by NicholasNoise** [comment]
Is it possible to publish new package to nuget.org?

**Comment by henck** [comment]
Sure! I've bumped the version number to 1.1.0 and pushed a new package to nuget.

**Comment by NicholasNoise** [comment]
Thank you again!
I have missed at first look that the assembly is unsigned and has no strong name. Can you add the signature and publish package after?

**Comment by NicholasNoise** [comment]
Checked package@1.1.0 - it does not contain changes made by this PR.

**Comment by henck** [comment]
I don't have much experience putting together nuget packages with Visual Studio...

I synced with the remote git repository, and my local codebase definitely is up to date. I did (re)build. Then I ran `nuget pack`, and pushed to nuget. I don't see where I went wrong! I'll give it another shot in a while, and sign the assembly while I'm at it.

**Comment by NicholasNoise** [comment]
I think I may help you on this issue.
I will send new PR, ok with that?

**Pull request merged**
